// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/absmach/supermq/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewKeyManager creates a new instance of KeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyManager {
	mock := &KeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyManager is an autogenerated mock type for the KeyManager type
type KeyManager struct {
	mock.Mock
}

type KeyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyManager) EXPECT() *KeyManager_Expecter {
	return &KeyManager_Expecter{mock: &_m.Mock}
}

// PublicKeys provides a mock function for the type KeyManager
func (_mock *KeyManager) PublicKeys() ([]auth.PublicKeyInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PublicKeys")
	}

	var r0 []auth.PublicKeyInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]auth.PublicKeyInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []auth.PublicKeyInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auth.PublicKeyInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyManager_PublicKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicKeys'
type KeyManager_PublicKeys_Call struct {
	*mock.Call
}

// PublicKeys is a helper method to define mock.On call
func (_e *KeyManager_Expecter) PublicKeys() *KeyManager_PublicKeys_Call {
	return &KeyManager_PublicKeys_Call{Call: _e.mock.On("PublicKeys")}
}

func (_c *KeyManager_PublicKeys_Call) Run(run func()) *KeyManager_PublicKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyManager_PublicKeys_Call) Return(publicKeyInfos []auth.PublicKeyInfo, err error) *KeyManager_PublicKeys_Call {
	_c.Call.Return(publicKeyInfos, err)
	return _c
}

func (_c *KeyManager_PublicKeys_Call) RunAndReturn(run func() ([]auth.PublicKeyInfo, error)) *KeyManager_PublicKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type KeyManager
func (_mock *KeyManager) Sign(key auth.Key) (string, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.Key) (string, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.Key) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(auth.Key) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyManager_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type KeyManager_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - key auth.Key
func (_e *KeyManager_Expecter) Sign(key interface{}) *KeyManager_Sign_Call {
	return &KeyManager_Sign_Call{Call: _e.mock.On("Sign", key)}
}

func (_c *KeyManager_Sign_Call) Run(run func(key auth.Key)) *KeyManager_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.Key
		if args[0] != nil {
			arg0 = args[0].(auth.Key)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyManager_Sign_Call) Return(signedToken string, err error) *KeyManager_Sign_Call {
	_c.Call.Return(signedToken, err)
	return _c
}

func (_c *KeyManager_Sign_Call) RunAndReturn(run func(key auth.Key) (string, error)) *KeyManager_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type KeyManager
func (_mock *KeyManager) Verify(tokenString string) (auth.Key, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 auth.Key
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (auth.Key, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) auth.Key); ok {
		r0 = returnFunc(tokenString)
	} else {
		r0 = ret.Get(0).(auth.Key)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyManager_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type KeyManager_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - tokenString string
func (_e *KeyManager_Expecter) Verify(tokenString interface{}) *KeyManager_Verify_Call {
	return &KeyManager_Verify_Call{Call: _e.mock.On("Verify", tokenString)}
}

func (_c *KeyManager_Verify_Call) Run(run func(tokenString string)) *KeyManager_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyManager_Verify_Call) Return(key auth.Key, err error) *KeyManager_Verify_Call {
	_c.Call.Return(key, err)
	return _c
}

func (_c *KeyManager_Verify_Call) RunAndReturn(run func(tokenString string) (auth.Key, error)) *KeyManager_Verify_Call {
	_c.Call.Return(run)
	return _c
}
