/*
 * SuperMQ Users Service
 *
 * This is the Users Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform users. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignUserReqObj {
    /// User IDs
    #[serde(rename = "user_ids")]
    pub user_ids: Vec<String>,
    /// Permission relations.
    #[serde(rename = "relation")]
    pub relation: String,
}

impl AssignUserReqObj {
    pub fn new(user_ids: Vec<String>, relation: String) -> AssignUserReqObj {
        AssignUserReqObj {
            user_ids,
            relation,
        }
    }
}

