/*
 * SuperMQ Certs service
 *
 * HTTP API for Certs service Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCertRequest {
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    #[serde(rename = "ttl")]
    pub ttl: String,
}

impl CreateCertRequest {
    pub fn new(client_id: uuid::Uuid, ttl: String) -> CreateCertRequest {
        CreateCertRequest {
            client_id,
            ttl,
        }
    }
}

