/*
 * SuperMQ Domains Service
 *
 * This is the Domains Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform domains. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteInvitationRequest {
    /// User unique identifier.
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl DeleteInvitationRequest {
    pub fn new(user_id: uuid::Uuid) -> DeleteInvitationRequest {
        DeleteInvitationRequest {
            user_id,
        }
    }
}

