/*
 * SuperMQ Journal Log Service
 *
 * This is the Journal Log Server based on the OpenAPI 3.0 specification.  It is the HTTP API for viewing journal log history. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@mainflux.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JournalPage {
    #[serde(rename = "journals")]
    pub journals: Vec<models::Journal>,
    /// Total number of items.
    #[serde(rename = "total")]
    pub total: i32,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset")]
    pub offset: i32,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl JournalPage {
    pub fn new(journals: Vec<models::Journal>, total: i32, offset: i32) -> JournalPage {
        JournalPage {
            journals,
            total,
            offset,
            limit: None,
        }
    }
}

