/*
 * SuperMQ Certs service
 *
 * HTTP API for Certs service Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Revoke {
    /// Certificate revocation time
    #[serde(rename = "revocation_time", skip_serializing_if = "Option::is_none")]
    pub revocation_time: Option<String>,
}

impl Revoke {
    pub fn new() -> Revoke {
        Revoke {
            revocation_time: None,
        }
    }
}

