/*
 * SuperMQ Certs service
 *
 * HTTP API for Certs service Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SerialsPage {
    /// Certificate serials IDs.
    #[serde(rename = "serials", skip_serializing_if = "Option::is_none")]
    pub serials: Option<Vec<String>>,
    /// Total number of items.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl SerialsPage {
    pub fn new() -> SerialsPage {
        SerialsPage {
            serials: None,
            total: None,
            offset: None,
            limit: None,
        }
    }
}

