/*
 * SuperMQ Journal Log Service
 *
 * This is the Journal Log Server based on the OpenAPI 3.0 specification.  It is the HTTP API for viewing journal log history. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@mainflux.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Telemetry {
    /// Unique identifier of the client
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<uuid::Uuid>,
    /// Unique identifier of the domain
    #[serde(rename = "domain_id", skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<uuid::Uuid>,
    /// Number of active subscriptions for the client
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<i64>,
    /// Number of messages received by the client
    #[serde(rename = "inbound_messages", skip_serializing_if = "Option::is_none")]
    pub inbound_messages: Option<i64>,
    /// Number of messages sent by the client
    #[serde(rename = "outbound_messages", skip_serializing_if = "Option::is_none")]
    pub outbound_messages: Option<i64>,
    /// Timestamp when the client was first seen
    #[serde(rename = "first_seen", skip_serializing_if = "Option::is_none")]
    pub first_seen: Option<String>,
    /// Timestamp when the client was last seen
    #[serde(rename = "last_seen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<String>,
}

impl Telemetry {
    pub fn new() -> Telemetry {
        Telemetry {
            client_id: None,
            domain_id: None,
            subscriptions: None,
            inbound_messages: None,
            outbound_messages: None,
            first_seen: None,
            last_seen: None,
        }
    }
}

