/*
 * SuperMQ Auth Service
 *
 * This is the Auth Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform users. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePatDescriptionRequest {
    /// New description for the Personal Access Token
    #[serde(rename = "description")]
    pub description: String,
}

impl UpdatePatDescriptionRequest {
    pub fn new(description: String) -> UpdatePatDescriptionRequest {
        UpdatePatDescriptionRequest {
            description,
        }
    }
}

