/*
 * SuperMQ Users Service
 *
 * This is the Users Server based on the OpenAPI 3.0 specification.  It is the HTTP API for managing platform users. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserUpdate {
    /// User's first name.
    #[serde(rename = "first_name")]
    pub first_name: String,
    /// User's last name.
    #[serde(rename = "last_name")]
    pub last_name: String,
    /// Arbitrary, object-encoded user's data.
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl UserUpdate {
    pub fn new(first_name: String, last_name: String, metadata: serde_json::Value) -> UserUpdate {
        UserUpdate {
            first_name,
            last_name,
            metadata,
        }
    }
}

