// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

package authn

import (
	"context"
	"encoding/base64"
	"errors"
	"strings"
)

type TokenType uint32

const (
	// AccessToken represents token generated by user.
	AccessToken TokenType = iota
	// PersonalAccessToken represents token generated by user for automation.
	PersonalAccessToken
)

func (t TokenType) String() string {
	switch t {
	case AccessToken:
		return "access token"
	case PersonalAccessToken:
		return "pat"
	default:
		return "unknown"
	}
}

type Role uint32

const (
	UserRole Role = iota + 1
	AdminRole
)

type Session struct {
	Type         TokenType
	PatID        string
	UserID       string
	DomainID     string
	DomainUserID string
	SuperAdmin   bool
	Role         Role
}

// Authn is supermq authentication library.
type Authentication interface {
	Authenticate(ctx context.Context, token string) (Session, error)
}

const (
	authSep = ":"

	BasicAuthPrefix  = "Basic "
	DomainAuthPrefix = "Domain "
)

// ErrNotEncoded acts similarly to EOF - it does indicate there is no suffix in
// the token, but that does not have to be treated as the error in some cases.
var ErrNotEncoded = errors.New("token is not encoded with domain ID suffix")

func AuthUnpack(token string) (string, string, string, error) {
	payload, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return "", "", "", err
	}
	s := string(payload)
	var prefix string
	switch {
	case strings.HasPrefix(s, BasicAuthPrefix):
		prefix = BasicAuthPrefix
		s = s[len(BasicAuthPrefix):]
	case strings.HasPrefix(s, DomainAuthPrefix):
		prefix = DomainAuthPrefix
		s = s[len(DomainAuthPrefix):]
	}
	key, id, found := strings.Cut(s, authSep)
	if !found {
		return prefix, key, id, ErrNotEncoded
	}
	return prefix, key, id, nil
}

func AuthPack(prefix, key, id string) string {
	return base64.StdEncoding.EncodeToString([]byte(prefix + key + ":" + id))
}
