// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broker/message.proto

package broker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Message represents a message emitted by the Mainflux adapters layer.
type Message struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Subtopic             string   `protobuf:"bytes,2,opt,name=subtopic" json:"subtopic,omitempty"`
	Publisher            string   `protobuf:"bytes,3,opt,name=publisher" json:"publisher,omitempty"`
	Protocol             string   `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
	ContentType          string   `protobuf:"bytes,5,opt,name=contentType" json:"contentType,omitempty"`
	Payload              []byte   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_0e5b34565349981b, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Message) GetSubtopic() string {
	if m != nil {
		return m.Subtopic
	}
	return ""
}

func (m *Message) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *Message) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Message) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "broker.Message")
}

func init() { proto.RegisterFile("broker/message.proto", fileDescriptor_message_0e5b34565349981b) }

var fileDescriptor_message_0e5b34565349981b = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2a, 0xca, 0xcf,
	0x4e, 0x2d, 0xd2, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x83, 0x88, 0x2a, 0x6d, 0x65, 0xe4, 0x62, 0xf7, 0x85, 0xc8, 0x08, 0x49, 0x70, 0xb1,
	0x27, 0x67, 0x24, 0xe6, 0xe5, 0xa5, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8,
	0x42, 0x52, 0x5c, 0x1c, 0xc5, 0xa5, 0x49, 0x25, 0xf9, 0x05, 0x99, 0xc9, 0x12, 0x4c, 0x60, 0x29,
	0x38, 0x5f, 0x48, 0x86, 0x8b, 0xb3, 0xa0, 0x34, 0x29, 0x27, 0xb3, 0x38, 0x23, 0xb5, 0x48, 0x82,
	0x19, 0x2c, 0x89, 0x10, 0x00, 0xe9, 0x04, 0x5b, 0x98, 0x9c, 0x9f, 0x23, 0xc1, 0x02, 0xd1, 0x09,
	0xe3, 0x0b, 0x29, 0x70, 0x71, 0x27, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x84, 0x54, 0x16, 0xa4,
	0x4a, 0xb0, 0x82, 0xa5, 0x91, 0x85, 0x40, 0x2e, 0x2a, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x91,
	0x60, 0x53, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0xa6, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xe5, 0x62, 0x25, 0xa9, 0xde, 0x00, 0x00, 0x00,
}
