# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fetch tags for the build
        run: |
          git fetch --prune --unshallow --tags

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache-dependency-path: "go.sum"

      - name: Set GOBIN
        run: echo "GOBIN=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Add GOBIN to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          make test

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV }}
          files: ./coverage/*.out
          verbose: true

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Compile check for rabbitmq
        run: |
          SMQ_MESSAGE_BROKER_TYPE=msg_rabbitmq make mqtt

      - name: Compile check for redis
        run: |
          SMQ_ES_TYPE=es_redis make mqtt

      - name: Build and push Docker images
        run: |
          make latest -j $(nproc)

      - name: Trigger Helm Chart Deployment
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: absmach/amdm
          event-type: deploy-latest-smq-images
